<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TKK5GPG" name="test.registeryahoo" tests="6" failures="1" timestamp="13 Nov 2016 14:58:16 GMT" time="0.004" errors="0">
  <testcase name="checkAssertions" time="0.002" classname="test.registeryahoo">
    <failure type="java.lang.AssertionError" message="expected:&lt;noGood&gt; but was:&lt;Good&gt;">
      <![CDATA[java.lang.AssertionError: expected:<noGood> but was:<Good>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:480)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at test.registeryahoo.checkAssertions(registeryahoo.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </failure>
  </testcase>
  <testcase name="checkTrueAssertions" time="0.001" classname="test.registeryahoo"/>
  <testcase name="checkfalseAssertions" time="0.001" classname="test.registeryahoo"/>
  <testcase name="register" time="0.000" classname="test.registeryahoo"/>
  <testcase name="register" time="0.000" classname="test.registeryahoo"/>
  <testcase name="register" time="0.000" classname="test.registeryahoo"/>
</testsuite>
